/**
 * Wallet Manager (Popup Side)
 *
 * High-level wallet management that communicates with service worker.
 * This file runs in the popup context and sends messages to the service worker
 * where WebZjs actually runs.
 *
 * Architecture:
 * Popup (UI) ← chrome.runtime.sendMessage → Service Worker (WebZjs)
 */

import { getVaultData } from './storage/secure-storage';
import { useWalletState } from './storage/wallet-state';
import { sendMessageToServiceWorker, generateRequestId } from '../types/messages';
import type { InitWalletResponse } from '../types/messages';

/**
 * Initialize the wallet system
 * This should be called when the extension starts
 */
export async function initializeWallet(): Promise<void> {
  console.log('[WalletManager] Initializing wallet system...');

  try {
    // Get vault data
    const vaultData = getVaultData();
    if (!vaultData) {
      console.log('[WalletManager] No vault data - wallet not created yet');
      return;
    }

    console.log('[WalletManager] Sending INIT_WALLET message to service worker...');

    // Send message to service worker to initialize WebZjs wallet
    const response = await sendMessageToServiceWorker<InitWalletResponse>({
      type: 'INIT_WALLET',
      requestId: generateRequestId(),
      data: {
        accountName: vaultData.accountName,
        seedPhrase: vaultData.seedPhrase,
        accountHdIndex: 0,
        birthdayHeight: vaultData.birthdayHeight || undefined,
      },
    });

    console.log('[WalletManager] ✅ Received response from service worker');
    console.log('[WalletManager] Account ID:', response.accountId);
    console.log('[WalletManager] Address:', response.address);

    // Update state
    const state = useWalletState.getState();
    state.setInitialized(true);
    state.setUnlocked(true);
    state.setAccountId(response.accountId);
    state.setAddress(response.address);

    console.log('[WalletManager] ✅ Wallet initialization complete!');
    console.log('[WalletManager] 🎉 REAL Zcash address generated by WebZjs!');

  } catch (error) {
    console.error('[WalletManager] Failed to initialize wallet:', error);
    throw error;
  }
}

/**
 * Check if wallet is ready to use
 */
export function isWalletInitialized(): boolean {
  return useWalletState.getState().isInitialized;
}

/**
 * Get current wallet address
 */
export function getWalletAddress(): string | null {
  return useWalletState.getState().address;
}

/**
 * Get current balance
 */
export function getWalletBalance(): bigint {
  return useWalletState.getState().balance;
}

/**
 * Sync wallet with blockchain
 */
export async function syncWalletData(): Promise<void> {
  const state = useWalletState.getState();

  if (!state.isInitialized) {
    throw new Error('Wallet not initialized');
  }

  try {
    state.setSyncing(true);

    // TODO: Implement real sync with WebZjs
    console.log('[WalletManager] Sync not yet implemented');

    state.setLastSyncTime(Date.now());
    state.setSyncProgress(100);

  } catch (error) {
    console.error('[WalletManager] Sync failed:', error);
    throw error;
  } finally {
    state.setSyncing(false);
  }
}

/**
 * Lock wallet (clear session)
 */
export function lockWallet(): void {
  const state = useWalletState.getState();
  state.reset();
  console.log('[WalletManager] Wallet locked');
}
